import "./globals.css";
import {
  ClerkProvider,
  SignedOut,
  SignedIn
} from '@clerk/nextjs'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <SignedOut>
          {children}
        </SignedOut>
        <SignedIn>
          {children}
        </SignedIn>
      </body>
    </html>
    </ClerkProvider>
  );
}
